# -*- coding: utf-8 -*-
"""Exoplanet Discovery - Data Science Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aKDkYrTQ9DuHjCWxB7wGmLw-kzp_Rp2r
"""

import pandas as pd
import numpy as np

# Load the data
exoplanets = pd.read_csv("/content/drive/MyDrive/Colab Files/exoplanets_discovered.csv", sep=',')

exoplanets

# List of discovery types
x = np.array(exoplanets['discoverymethod'])
discovery_types = np.unique(x)

discovery_types

# List of years
year_start = min(exoplanets["disc_year"]-3)
year_end = max(exoplanets["disc_year"])
print(year_start, " - ", year_end)

# Make array of year and types
exoplanets_years = pd.DataFrame()
for year in range(year_start, year_end+1):
  discovery_type_list = []
  for index, discovery_type in enumerate(discovery_types):
    numPlanets = 0 
    if year > year_start:
      # numplanets is the cumulative total
      numPlanets = exoplanets_years.at[index,year-1]
    numPlanets += pd.Series.sum((exoplanets['disc_year'] == year) & (exoplanets['discoverymethod'] == discovery_type))
    discovery_type_list.append(numPlanets)
  exoplanets_years[year] = discovery_type_list
exoplanets_years.insert(0, "Discovery Type", discovery_types)

exoplanets_years

exoplanets_years.to_csv(index=False)